all:pripds ids getname system child execve waiter killer fkill killEmacs mkset block pending

pripds:pripds.o

ids:ids.o

getname:getname.o

system:system.o

child:child.o

execve:execve.o

waiter:waiter.o

killer:killer.o

fkill:fkill.o

killEmacs:killEmacs.o

mkset:mkset.o

block:block.o

pending:pending.o